- name: Create OSD Instances
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Launch instance
      ec2:
         group_id: {{ ceph.sg }}
         count: 3
         instance_type: {{ ceph.osd.instance_type }}
         image: {{ ceph.ami }}
         wait: true
         region: {{ ceph.region }}
         vpc_subnet_id: {{ ceph.subnet.pub }}
         assign_public_ip: yes
         instance_tags:
           Name: {{ ceph.osd.name }}
         volumes:
           - device_name: /dev/sda1
             volume_type: gp2
             volume_size: 10
             delete_on_termination: true
           - device_name: /dev/sdb
             volume_type: gp2
             volume_size: 10
             delete_on_termination: true
           - device_name: /dev/sdc
             volume_type: gp2
             volume_size: 10
             delete_on_termination: true
      register: ec2

    - ec2_eni:
        subnet_id: {{ ceph.subnet.priv }}
        state: present
        secondary_private_ip_address_count: 1
        security_groups: {{ ceph.sg }}
        region: {{ ceph.region }}
        device_index: 1
        description: "Eagle-Ceph-Cluster-Interface"
        instance_id: "{{ '{{' }} item.id {{ '}}' }}"
        attached: yes
      with_items: "{{ '{{' }} ec2.instances {{ '}}' }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ '{{' }} item.public_ip {{ '}}' }}"
        groupname: osds
      with_items: "{{ '{{' }} ec2.instances {{ '}}' }}"

    - name: Update Inventory
      command: /usr/local/bin/ansible-inventory.sh osds "{{ '{{' }} item.public_ip {{ '}}' }}"
      with_items: "{{ '{{' }} ec2.instances {{ '}}' }}"

- name: Create MON Instances
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Launch instance
      ec2:
         group_id: {{ ceph.sg }}
         count: 3
         instance_type: {{ ceph.mon.instance_type }}
         image: {{ ceph.ami }}
         wait: true
         region: {{ ceph.region }}
         vpc_subnet_id: {{ ceph.subnet.pub }}
         assign_public_ip: yes
         instance_tags:
           Name: {{ ceph.mon.name }}
         volumes:
           - device_name: /dev/sda1
             volume_type: gp2
             volume_size: 10
             delete_on_termination: true
      register: ec2

    - ec2_eni:
        subnet_id: {{ ceph.subnet.priv }}
        state: present
        secondary_private_ip_address_count: 1
        security_groups: {{ ceph.sg }}
        region: {{ ceph.region }}
        device_index: 1
        description: "Eagle-Ceph-Cluster-Interface"
        instance_id: "{{ '{{' }} item.id {{ '}}' }}"
        attached: yes
      with_items: "{{ '{{' }} ec2.instances {{ '}}' }}"

    - name: Add new instance to host group
      add_host:
        hostname: "{{ '{{' }} item.public_ip {{ '}}' }}"
        groupname: mons
      with_items: "{{ '{{' }} ec2.instances {{ '}}' }}"

    - name: Update Inventory
      command: /usr/local/bin/ansible-inventory.sh mons "{{ '{{' }} item.public_ip {{ '}}' }}"
      with_items: "{{ '{{' }} ec2.instances {{ '}}' }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ '{{' }} item.public_dns_name {{ '}}' }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ '{{' }} ec2.instances {{ '}}' }}"

- name: Configure instance(s)
  hosts: 
  - osds 
  - mons
  gather_facts: false
  become: True
  roles:
    - rhel7-base
    - add-nic
